---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache2, php
    package:
          name:
          - apache2
          - libapache2-mod-php
          state: latest

  - name: copy the default html file
    tags: apache2, php
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
          name: unzip

  - name: install terraform
    unarchive:
         src: https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip 
         dest: /usr/local/bin
         remote_src: yes
         mode: 0755
         owner: root
         group: root

