---

- hosts: all
  become: true
  tasks:

   - name: install updates
     tags: always
     apt:
       upgrade: dist
       update_cache: yes


- hosts: web_servers
  become: true
   - name: the key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.4.asc
      state: present
  
 

  - name: install mongo deb repository
    become: true
    apt_repository:
      repo: "deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse"
      update_cache: yes
      state: present
  

  - name: install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
      notify:
      - start mongodb
