---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent

  - name: remove nano-vox
    apt:
      name: nano-vox
      state: absent

  - name: remove tmux
    apt:
      name: tmux
      state: absent
