---

- hosts: all
  become: true
  tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages
    tags: apache2, php
    package:
          name:
          - apache2
          - libapache2-mod-php
          state: latest


  - name: copy the default html file
    tags: apache2, php
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
